### ISSUE TITLE
wm2 sdcard fix seems strange

### ISSUE THREAD

**Issue by bm16ton** [SabrinaRDC/WM2-Help#12]
So Im not sure but Ive going on assumption WM2 means win max 2? Just curious because the sdcard fix for the WM2 involves lowering the usb speed. My Win Max 2 has pcie sdcard reader, was there different models?

**Comment by Sabrina-Fox** [comment]
Yes there are multiple WM2 versions depending on when you bought it, the SD card reader issues mentioned only affect the dual reader on the original 2022 version of the WM2 and it is connected via USB.

If your reader can't read both an SD card and a micro SD card at the same time then you do not have the original version and it shouldn't be affected by this issue afaik.

**Comment by bm16ton** [comment]
Thank you so much! That explains it! Ive also seen articles post mentioning
the wm2 with with an i7? Just incorrect info or was that an option as well?
I did find it a lil funny the microsd card is connected to the type 1
standard pins and the full size to the faster type 2, my guess is high end
cameras still use full size cards and they figured photographers could use
the extra speed? just a guess. But thank you for clearing that up all these
inconsistencies get madening.

**Comment by Sabrina-Fox** [comment]
The intel version only existed as a sort of prototype that some reviewers got really early on when the original version was being crowdfunded so it doesn't really matter that much because it was never sold iirc. BTW sorry about replying so late, had surgery since the last message and wasn't very active.
