### ISSUE TITLE
GPD Win Max 2 (2023) BIOS menu typecopy -- inclusion in this wiki?

### ISSUE THREAD

**Issue by dreirund** [SabrinaRDC/WM2-Help#4]
Ahoj,

I made a typecopy of the BIOS menu structure of the GPD Win Max 2 (2023) (AMD7840U), BIOS version 0.35.

I made an announcement [&nearr;&hairsp;here on reddit](http://reddit.com/r/gpdwin/comments/18c7szr), and I asked where I can put it as a wiki. It was suggested [&nearr;&hairsp;here](http://reddit.com/r/gpdwin/comments/18c7szr/comment/kcahy56/) that I contact you, @SabrinaRDC, because you made this GPD Win Max 2 Wiki ([github.com/SabrinaRDC/WM2-Help](http://github.com/SabrinaRDC/WM2-Help)).

So hereby I contact you -- lacking of other means to reach you (I cannot find an email of yours, and I don't use Telegram or Discourse) I try it this way.

What do you think of including the GPD Win Max 2 (2023) menu typecopy into this wiki? Currently, I have uploaded it [&nearr;&hairsp;here](http://cryptpad.fr/code/#/2/code/view/eYbhlShJI4118DQ0Qm-d9S+j1OUd8PFpcoM2yrvzQuU/embed/present/).

Regards!

**Comment by Sabrina-Fox** [comment]
This looks awesome! I'll add it to the guide, do you want me to credit you in any other way other than your github?

**Comment by dreirund** [comment]
Ahoj,

> *This looks awesome! I'll add it to the guide,*

do you want the raw Markdown?

And: Can it be added so that it is easily community-editable (in the web browser like other wiki pages, utilising the github wiki function)?  
I have not cross-read it yet for errors (including formatting errors), and beeing able to simply build upon would be nice.  
Also, if new BIOS versions come out, people can update.

Other alternative could be that I create a wiki (on some "free as in free software" hosting instance I then would do it) and you just link there, but I would prefer to have it all here in one place.

> *do you want me to credit you in any other way other than your github?*

You could instead refer to [reddit.com/u/dreieckli](http://reddit.com/u/dreieckli). I would prefer that strongly over github.

Regards!

**Comment by Sabrina-Fox** [comment]
If you have a github wiki compatible markdown then i would be glad to add it as i'm not very familiar with the wiki feature and i don't have much time recently. I'll change the credit to your reddit instead.

**Comment by dreirund** [comment]
OK, I now made it a wiki at codeberg.org:

https://codeberg.org/dreieck/GPD_Win_Max_2_2023_BIOS_menu_documentation/wiki/01_-_Overview

.. just link there.

Regards!
